### ISSUE TITLE
theme generator bug

### ISSUE THREAD

**Issue by sxlwar** [helix-bridge/helix-ui#1]
每次编译总是这几个 class 变来变去，右侧为编译结果

<img width="1887" alt="WX20220411-171935@2x" src="https://user-images.githubusercontent.com/20088392/162708857-82e6738e-d2bf-448a-b74e-ad02dbd3a38b.png">

![image](https://user-images.githubusercontent.com/20088392/162708992-0525e5df-cbeb-4869-bf39-aac38fe7198c.png)

**Comment by sxlwar** [comment]
build:  生成color.less 供 less.js 在客户端使用。生成light.less 供服务端使用。

server: 根据路由参数动态引入 CSS

client：首次渲染完成后加载 less.min.js & color.js ; 切换主题时由 less.js 生成样式文件

**Comment by xiaoch05** [comment]
组件白框问题还存在，背景已经解决
