### ISSUE TITLE
Optimize banlace display

### ISSUE THREAD

**Issue by sxlwar** [helix-bridge/helix-ui#113]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

Low

### Reproduce steps

connect to a Darwinia-type chain then check the balance

<img width="413" alt="image" src="https://user-images.githubusercontent.com/20088392/180371554-7c2740e4-a53c-4fc0-b23f-ee89e1ee2d28.png">

### Actual behavior

the balance is total

### Expected behavior

Display total and available amount

**Comment by ZolaxZola** [comment]
related to #135
