### ISSUE TITLE
Dashbord bug about transactions chart

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#114]
### Prerequisites

- [X] Are you running the latest version?

### Importance

Serious

### Priority

High

### Reproduce steps

![dashboard bug](https://user-images.githubusercontent.com/102211220/180716143-3354e841-4283-44b7-aa62-1dd50b985031.png)

### Actual behavior

- [ ] Transaction Counting is wrong
To take `data of July 19, 2022`  for example, the count(transactions) was supposed to be 32 

- [ ] The inconsistent relationship between bar chart height and data
It shows transaction counting is equal on 18, July and 19, July (they are both 1 transaction). But the bar chart height of 19, July is twice higher as that of 18, July. We should double-check here.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/102211220/180717329-19948d46-a05e-4a52-ab13-a4c9f923ab10.png"> 

### Expected behavior

1. Show the accurate data preview of transactions counting
2. Bar chart height in relation to data

**Comment by sxlwar** [comment]
design changed
