### ISSUE TITLE
The transaction history empty in the test env.

### ISSUE THREAD

**Issue by AsceticBear** [helix-bridge/helix-ui#121]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

Medium

### Reproduce steps

Reproduce: Cross-chain transfer from `Pangolin-Smart-Chain XORING` to `Pangoro`

### Actual behavior

![image](https://user-images.githubusercontent.com/11801722/181207724-9285bc42-212f-431f-a475-954b0d56c2be.png)

![image](https://user-images.githubusercontent.com/11801722/181208183-ee4af8f8-cbed-4244-a8da-9b963b37b4bb.png)

The [transaction](https://pangolin.subscan.io/extrinsic/3410424-1) succeed, but the history is empty

### Expected behavior

Show the cross-chain history correctly.

### Please provide the environment you discovered this bug in

Env: https://helix-apps-test-stg.vercel.app/zh

### Anything else?

No

**Comment by sxlwar** [comment]
This is most likely the helix indexer issue. In the future, the history of the test networks may not work properly because of we have no more subql indexer for it.
