### ISSUE TITLE
Wrong Transferrable Amount of Crab Chain Address

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#135]
### Prerequisites

- [X] Are you running the latest version?

### Importance

Serious

### Priority

High

### Reproduce steps

![image](https://user-images.githubusercontent.com/102211220/181429416-6b606553-8238-4d88-a7f0-d3a507803200.png)
![image](https://user-images.githubusercontent.com/102211220/181429446-62e081ff-1547-4919-815a-cc5c78c9e8bf.png)
![image](https://user-images.githubusercontent.com/102211220/181429488-c9957f36-3ace-4ef1-bb57-7972a52f1ad7.png)

### Actual behavior

When I put in the amount the UI show me
I can submit the transfer without any reminder but get a Failure Result 
`InsufficientBalance`
https://crab.subscan.io/extrinsic/0x0adf9d20a0b7f890fac05070b886c189227dcc5e718036f02857f980b150558b

### Expected behavior

- [ ] Show me the right transferrable balance

- [ ] Remind me if the balance is Insufficient

**Comment by ZolaxZola** [comment]
The Same on Crab Parachian 
https://crab-parachain.subscan.io/extrinsic/639543-2   Transaction Failed`（InsufficientBalance）`

**Comment by sxlwar** [comment]
duplicated #113
