### ISSUE TITLE
Darwinia>Ethereum  Transaction Failed （InsufficientBalance）

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#154]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

Medium

### Reproduce steps

When filling in the transferable balance that displayed in the transfer amount 
the tx is successfully submitted but failed because of the `（InsufficientBalance）`
the transferable balance is wrong here

### Actual behavior

https://darwinia.subscan.io/extrinsic/9640930-1

### Expected behavior

- [ ] show the correct transferrable amount (880.672 rather than 1000.672)

<img width="537" alt="image" src="https://user-images.githubusercontent.com/102211220/182377499-136786b8-e5e8-43c9-9bbb-4b1c4fa5381d.png">
<img width="867" alt="image" src="https://user-images.githubusercontent.com/102211220/182377733-ff1d5b69-8e4b-42d7-98e5-2bce5f99877c.png">

- [ ] offer an alert if the amount is beyond the correct transferable balance

**Comment by sxlwar** [comment]
duplicated with #113
