### ISSUE TITLE
 Gas Fee from BSC seems too high

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#189]
### Prerequisites

- [X] Are you running the latest version?

### Importance

Serious

### Priority

Medium

### Reproduce steps

![image](https://user-images.githubusercontent.com/102211220/186556009-83859ab1-a512-4014-ac68-482d7a8bccf8.png)

### Actual behavior

gas shows 0.35 BNB, which is expected to be 0.000X BNB

### Expected behavior

a lower gas fee of BNB

**Comment by xiaoch05** [comment]
some token should be mint on target chain, and use different call.
The parameter is is_pegged.

**Comment by ZolaxZola** [comment]
has been resolved
