### ISSUE TITLE
No record for USDC.e (Avalanche) > USDC (Astar) 

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#201]
https://snowtrace.io/tx/0x57c65d9488278002facd463ab52f9a9da2414bc2a06f635d6268f8d04b6ba25c
The tx is successful  but no records can be found on `Transfer History` or `Explorer `

**Comment by xiaoch05** [comment]
fixed https://github.com/helix-bridge/indexer/commit/950b5d96d604e6febd1ee0e56591a59efd253823
