### ISSUE TITLE
the source hash on BNB chain is unavailable

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#206]
the source hash on BNB Chain: https://bsc.etherscan.io/tx/0xd0e7450408c7f0ac9b42c38afd5a89f4f9c222085394396a8acff31ff529ed2d, which is unavailable.
shall we change it into:
https://bscscan.com/tx/0xd0e7450408c7f0ac9b42c38afd5a89f4f9c222085394396a8acff31ff529ed2d
<img width="856" alt="image" src="https://user-images.githubusercontent.com/102211220/187208771-2809f31d-f090-49da-8219-19fbfbe172e1.png">

**Comment by ZolaxZola** [comment]
- [ ] this tx has been completed hours ago, but it shows `pending `all the time

**Comment by ZolaxZola** [comment]
- [ ] when transferring USDC(BNB chain) to USDC.e (Avalanche), both USDC.e and a little bit `AVAX `(like 0.42 AVAX) should both be received.  I haven't received `AVAX` today. Maybe we should check this.
( ASTR is [received](https://blockscout.com/astar/address/0x2FDeEc247037a343b26F5dAa0d3aF15fe23a28C5/transactions#address-tabs) when transferring USDC.e (Avalanche) to USDC(Astar).

**Comment by xiaoch05** [comment]
> * [ ]  when transferring USDC(BNB chain) to USDC.e (Avalanche), both USDC.e and a little bit `AVAX `(like 0.42 AVAX) should both be received.  I haven't received `AVAX` today. Maybe we should check this.
>   ( ASTR is [received](https://blockscout.com/astar/address/0x2FDeEc247037a343b26F5dAa0d3aF15fe23a28C5/transactions#address-tabs) when transferring USDC.e (Avalanche) to USDC(Astar).

For whether we can receive additional native token, this is an additional mechanism of cBridge, we don't need to care about it, this time we can't receive it probably because this account already has enough AVAX for the fee.

**Comment by xiaoch05** [comment]
fixed by https://github.com/helix-bridge/indexer/commit/950b5d96d604e6febd1ee0e56591a59efd253823
