### ISSUE TITLE
Refund： USDT（Arbitrum）> (Optimism)

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#210]
<img width="831" alt="image" src="https://user-images.githubusercontent.com/102211220/187376188-e42e3427-64f1-4da2-af64-cf908c00b785.png">

https://arbitrum.etherscan.io/tx/0x7d872760b8ecc19a4cde70ff3e0bac4c12739500d82da14dabdb527256cff0da

**Comment by ZolaxZola** [comment]
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/102211220/187376518-06539775-a4d9-4549-a883-b896d9e9ce5a.png">

**Comment by sxlwar** [comment]
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/20088392/202638168-45f7a2b2-c927-4d2e-966d-4cd0e77bb55d.png">

**Comment by xiaoch05** [comment]
https://helixbridge.app/records/cbridge/arbitrum-10-cbridge-0xe5d2687f1e105204c2b9cb5cd032e3721f92e5560c602692a17f996bc4f62dc3
