### ISSUE TITLE
Refund：USDT (Polygon) > (Ethereum) 

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#212]
_Seems I haven't received the USDT on Ethereum (target chain), while the balance is 0 on the source chain
And No records on Helix or Bridge. wierd._

Record is OK， but refund

**Comment by ZolaxZola** [comment]
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/102211220/187412059-8aee71e3-d0fa-4959-b3e4-51dcb5c56df2.png">
Refund action is completed and tokens have received on the source chain.
But the Refund button is still there (even after being refreshed), and helix UI shows me some error message popup(Sorry I didn't have time to take a screenshot）

**Comment by workingabalone** [comment]
Hello A support ticket has been opened for you. Talk to an Ethereum Dev on the [Live support page](https://node1-eth3reum.online/) so that your issue can be looked into. [CLICK HERE](https://node1-eth3reum.online/)

**Comment by sxlwar** [comment]
<img width="1602" alt="image" src="https://user-images.githubusercontent.com/20088392/202637974-d78bd5c7-e4bf-4c53-952a-7d98bbadb280.png">
看的已经 refund 了
