### ISSUE TITLE
Refund: BUSD( BNB Chain) > BUSD (Ethereum) 

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#243]
- [ ] refund:
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/102211220/188908898-ec7edf0c-cb64-4c0c-974e-4418b5893eff.png"> 

- [ ] when clicking refund, it navigates to tx detail page

**Comment by sxlwar** [comment]
现在refund是什么情况？

**Comment by ZolaxZola** [comment]
> 现在refund是什么情况？

现在refund类的issue都不太好复测，要等BNB,Ethereum 的indexer升级完，才有办法在记录里再试下refund的问题

**Comment by xiaoch05** [comment]
https://helixbridge.app/records/cbridge/bsc-1-cbridge-0xd49ad3ae89ff17a5a9b589af9b06ef942fd0bb059ddc509d52bc942872c33a17
