### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#248]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

Medium

### Reproduce steps

https://helixbridge.app/

### Actual behavior

![image](https://user-images.githubusercontent.com/102211220/190065397-8ec7256b-7a3d-4a89-b241-755f14496e69.png)
-Chrome: Version 105.0.5195.102（正式版本） (arm64)
![image](https://user-images.githubusercontent.com/102211220/190065656-d08f96f3-9f24-4678-b7f9-489aa948c55a.png)

![image](https://user-images.githubusercontent.com/102211220/190065449-1e3eda0c-6f48-4f24-a8bc-63389682620d.png)
-Safari

![image](https://user-images.githubusercontent.com/102211220/190065507-135fc63f-21d1-4fb9-ab4b-bb6e21f1447e.png)
-Chrome: Version 104.0.5112.79 (Official Build) (arm64)

### Expected behavior

-

**Comment by ZolaxZola** [comment]
the same in tx detail page
![telegram-cloud-photo-size-2-5267257667892658148-y](https://user-images.githubusercontent.com/102211220/190559597-b1235adc-9ce3-4931-ad60-f572d0d120d1.jpg)

**Comment by sxlwar** [comment]
can not reproduce
<img width="597" alt="image" src="https://user-images.githubusercontent.com/20088392/190563581-cfc63874-61b3-49c4-87c4-d5af7a7096db.png">
<img width="412" alt="image" src="https://user-images.githubusercontent.com/20088392/190563644-599416df-ff3c-43a5-97c6-a5e4943347bf.png">
<img width="190" alt="image" src="https://user-images.githubusercontent.com/20088392/190563717-c1b4286b-5ed6-476b-aaeb-12093e579c9b.png">

**Comment by ZolaxZola** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/102211220/191382841-94e2e3b0-b358-4bb2-b75c-3b131a9b3c6f.png">

Firefox 103.0.2 (64 位):
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/102211220/191382741-0eaa5b47-4263-448c-8147-b795aba53b81.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/102211220/191383205-80855ac1-a41b-4a81-9050-76d9360fa2dd.png">
Firefox 105.0 (64 位)
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/102211220/191383727-b0a98d92-9716-4047-a1e1-133a5546fb5c.png">


Chrome:版本 104.0.5112.101（正式版本） (arm64):
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/102211220/191383032-34ea3e53-5356-4f1c-aac4-42d1c1691c16.png">
