### ISSUE TITLE
Refunded state in personal history record

### ISSUE THREAD

**Issue by sxlwar** [helix-bridge/helix-ui#255]
### Topic

User Experience

### Description

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/20088392/191182288-d22c0ed5-3138-4e53-9613-d8e19cc108e1.png">

click to refund

After the request is sent, if the processing on the chain is not completed for a long time, the status in the indexer is always 1 which means pending refund.

At the front end, it will keep a temporary refunded list that holds all sent requests. So it will display 'refunded' after the request is sent, but if the user reloads the page, it will show the refund button again.

**Comment by xiaoch05** [comment]
The prompt here needs to be designed to allow the user to retry, but it also needs to indicate that the user has already tried to refund. @ZolaxZola

**Comment by ZolaxZola** [comment]
> The prompt here needs to be designed to allow the user to retry, but it also needs to indicate that the user has already tried to refund. @ZolaxZola

I think it's why cBridge offers button of 2 statuses here.  (maybe?
1: Request Refund
2. Confirm Refund

We could just learn from it. @sxlwar @xiaoch05

**Comment by xiaoch05** [comment]
> 

We have different scenario, we need to support retries, but can't tell if the current refund transaction has failed or is in a pending state

**Comment by xiaoch05** [comment]
has been fixed by adding a new state pendingForRefund in indexer.
