### ISSUE TITLE
Helix Beta Buglist

### ISSUE THREAD

**Issue by 1022ranji** [helix-bridge/helix-ui#27]
### Importance

General

### Priority

High

### Description

- [x] The target chain/token is not limited according to the source chain/token.
- [x] The same chain uses different tag colors.
![image](https://user-images.githubusercontent.com/80877629/168258452-b82f9ccf-5706-4d1f-a0e6-50c7098d817a.png)

**Comment by 1022ranji** [comment]
- [ ] Wrong Theme Color
![image](https://user-images.githubusercontent.com/80877629/168259804-bf107dcd-a271-4a4a-98d3-21ed9b6281f5.png)
Please adjust like below:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/80877629/168259935-e989e82a-f754-42c5-8760-35a98dd4d699.png">

**Comment by 1022ranji** [comment]
- [ ] Wrong Amount Display
![image](https://user-images.githubusercontent.com/80877629/168260456-8060803e-b5a1-4051-a217-1a1e490d77d9.png)

**Comment by ZolaxZola** [comment]
- [ ] `Wrong network alert` should be above the `「Transfer」` button not in the top right corner of the page, refer to image2

![image](https://user-images.githubusercontent.com/102211220/168261122-0617fc28-b8f0-4e3d-a279-6324da3f5e39.png)
![image](https://user-images.githubusercontent.com/102211220/168261192-ca925dad-02b5-4da2-9e23-9fad05834242.png)

**Comment by ZolaxZola** [comment]
- [ ] The token name of the Ethereum Network should be` ETH`
![image](https://user-images.githubusercontent.com/102211220/168262536-728ac4e9-fa68-4814-ba8a-d91cc6860e4d.png)

**Comment by xiaoch05** [comment]
- [ ] Two selection boxes are not aligned

![image](https://user-images.githubusercontent.com/15799431/168545857-4b7554d6-1f19-4c82-b8d0-d2d129971e3a.png)

**Comment by xiaoch05** [comment]
There should not be a white background border
![image](https://user-images.githubusercontent.com/15799431/168546378-c981f838-c2f4-4f31-9997-c19e796f81bc.png)

**Comment by ZolaxZola** [comment]
- [ ] Here should be an insufficient **balance alert**（which is missing）and an Insufficient **cross-chain fees alert** （which is now confused with transfer amount）

![image](https://user-images.githubusercontent.com/102211220/170188575-19682fae-4379-4caf-9a93-62e5729998bf.png)

![image](https://user-images.githubusercontent.com/102211220/170188389-4ceb4025-0ad5-4b8e-bea7-bc65032a001a.png)

**Comment by ZolaxZola** [comment]
when the balance is ok, the transaction fee is sufficient in my connected account， it still sends me this alert and stops me from transferring. Maybe something wrong here.
![why cannot transfer](https://user-images.githubusercontent.com/102211220/170192149-6fc4ddda-9d06-4962-897a-dfc06f7d670b.png)

**Comment by ZolaxZola** [comment]
- [ ] when approving allowance, I receive a  popup like this (which seems like the wrong time to be there）

![image](https://user-images.githubusercontent.com/102211220/170192276-b3fc9cae-6786-4b0a-8f0a-8b1209fdc7e5.png)

**Comment by ZolaxZola** [comment]
### Style issues, typos, and reminder-related issues

- [ ] 1.  The first amount should be in red color and the Minus sign is lost

- [ ] 2. In front of the second amount, the plus sign is lost

- [ ] 3.  Current address format mistake

- [ ] 4.  We need to change the logo to Darwinia Network Logo instead of Polkadot {.js}

- [ ] 5. May the reminder be wrong here?

![image](https://user-images.githubusercontent.com/102211220/170202905-c71d6ec1-5e53-4605-8294-5d99c0cb61f4.png)
- [ ] 6. When the transfer is submitted, the link in the popup in the right corner may be wrong, it navigates to the wrong URL.
![image](https://user-images.githubusercontent.com/102211220/170203028-022a509b-0513-4798-9df4-11e1b5e63145.png)


- [ ] 7.  Alert content should be in English here

![image](https://user-images.githubusercontent.com/102211220/170203576-f24b2448-e332-493f-9fc0-1b7ed60a75b0.png)
8. the estimated token amount I‘ll receive on the target chain should be displayed ( even I haven’t selected a bridge then)
![image](https://user-images.githubusercontent.com/102211220/170203619-7d8f016a-769d-4009-856c-51993126981e.png)

- [ ] Can we remove the white borders when selecting active account?
![image](https://user-images.githubusercontent.com/102211220/170203758-7285edf9-ce92-49d9-bdda-4eb08f2feed1.png)

- [ ] `Connect Wallet` could be better
![image](https://user-images.githubusercontent.com/102211220/170204129-7f2bd89c-cc51-4ae6-8a8f-1636befc3555.png)

**Comment by ZolaxZola** [comment]
after approving， the provided link here is https://crab.etherscan.io/tx/0xec069d87cb27b1440d40818e8bdb5624996bd9a39e883720d88bdde9205e7995
which is unavailable on Etherscan now, should we change into https://crab.subscan.io/tx/0xec069d87cb27b1440d40818e8bdb5624996bd9a39e883720d88bdde9205e7995
![image](https://user-images.githubusercontent.com/102211220/170221897-c5dd868b-5630-4017-b42b-35286c77758c.png)

**Comment by ZolaxZola** [comment]
- [ ] The`xKTON` Option  should be removed (which is not supported for transferring yet)
![image](https://user-images.githubusercontent.com/102211220/170457485-f0ffd04f-009c-45d3-baaf-97f4409f8e9f.png)

- [ ] The WCKTON Option should not be selected successfully. The selected function for WCKTON needs to be disabled
(Because we won’t offer an available bridge for transferring WCKTON in Helix bridge any longer. Only a jump link to Apps is provided )
![image](https://user-images.githubusercontent.com/102211220/170457677-5752fc3f-8389-4943-8f2e-0f93e9189f43.png)

**Comment by xiaoch05** [comment]
> ### Style issues, typos, and reminder-related issues
> * [x]  1.  The first amount should be in red color and the Minus sign is lost
> * [x]  2. In front of the second amount, the plus sign is lost
> * [ ]  3.  Current address format mistake
> * [ ]  4.  We need to change the logo to Darwinia Network Logo instead of Polkadot {.js}
> * [x]  5. May the reminder be wrong here?
> 
> ![image](https://user-images.githubusercontent.com/102211220/170202905-c71d6ec1-5e53-4605-8294-5d99c0cb61f4.png)
> 
> * [ ]  6. When the transfer is submitted, the link in the popup in the right corner may be wrong, it navigates to the wrong URL.
>   ![image](https://user-images.githubusercontent.com/102211220/170203028-022a509b-0513-4798-9df4-11e1b5e63145.png)
> * [ ]  7.  Alert content should be in English here
> 
> ![image](https://user-images.githubusercontent.com/102211220/170203576-f24b2448-e332-493f-9fc0-1b7ed60a75b0.png)
> 
> * [ ]  8. the estimated token amount I‘ll receive on the target chain should be displayed ( even I haven’t selected a bridge then)
> 
> ![image](https://user-images.githubusercontent.com/102211220/170203619-7d8f016a-769d-4009-856c-51993126981e.png)
> 
> * [ ]  Can we remove the white borders when selecting active account?
>   ![image](https://user-images.githubusercontent.com/102211220/170203758-7285edf9-ce92-49d9-bdda-4eb08f2feed1.png)
> * [ ]  `Connect Wallet` could be better
>   ![image](https://user-images.githubusercontent.com/102211220/170204129-7f2bd89c-cc51-4ae6-8a8f-1636befc3555.png)

- [ ] Do not use abbreviations for the address in the confirmation box.

**Comment by xiaoch05** [comment]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/15799431/170633145-18aa26a8-1d03-4248-a469-633b48893e5a.png">
- [ ]  Already connected the wallet, prompting the need to connect

**Comment by xiaoch05** [comment]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/15799431/170633456-8eb37fec-f54a-482a-82aa-416830e53281.png">

- [ ] delete the ckton support

**Comment by xiaoch05** [comment]
![image](https://user-images.githubusercontent.com/15799431/170634069-b6e9c079-6b70-46ba-a331-24c31ff2c41d.png)

- [ ] should link to the tx instead of the block.

**Comment by sxlwar** [comment]
切换网络按钮 replace badge with button
token select button: add chain logo

**Comment by ZolaxZola** [comment]
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/102211220/170935968-4c4a8b35-609d-4803-a2cc-e86c5e510677.png">

- [ ] The estimated amount that I will receive on the target chain is missing

**Comment by ZolaxZola** [comment]
- [ ] **cannot** find the transfer record（https://darwinia.subscan.io/extrinsic/0xdb2d63ab88dd095ab7e01f6f8274ba6c1bb9cb3667cbb02522e76357faf74ffc）

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/102211220/170937193-60e01d35-071c-4af0-828e-77b3d3e95cf2.png">

**Comment by ZolaxZola** [comment]
- [ ] Cannot find my transfer record （after completing transferring and clicking the `cross-chain history` button

![image](https://user-images.githubusercontent.com/102211220/170939091-93a6c3c9-3bb0-4572-8a47-f0d53ae6c367.png)

When I navigate to `Claim` page and come back to Ethereum<> Darwinia History page, the record appears.
Whne I Disconnect and connect polkadot {.js}  again, the record is missing, and Address format starts with 5
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/102211220/170940136-39db8114-ddc7-476b-a8d5-189a72ccece0.png">
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/102211220/170940265-eb2b16fd-4e3e-4d4c-ab06-e3b7e26d96f4.png">
I have to click the address starting with 2 then got the record. Here may be quite confusing.

**Comment by ZolaxZola** [comment]
- [ ] The accounts in the `receiver ` dropbox are incorrect. And it stops me from transferring. It needs to be a valid Darwinia address format here.

![image](https://user-images.githubusercontent.com/102211220/171088650-b594d271-7995-409c-a7de-fcfd0a481158.png)

**Comment by ZolaxZola** [comment]
- [ ] Transaction Fee is incorrect in the confirmation box

![image](https://user-images.githubusercontent.com/102211220/171089410-513becf8-ec48-4510-94b7-6b3bbddc6404.png)

**Comment by xiaoch05** [comment]
- [ ] Give the transfer amount enough space to display

![image](https://user-images.githubusercontent.com/15799431/171113724-1c9e8002-69c5-4719-9601-7fd4cd984719.png)

**Comment by xiaoch05** [comment]
- [ ] The first time the history page is opened and refreshed the displayed results do not match

https://user-images.githubusercontent.com/15799431/171119091-e10469d6-bfbf-4640-bdd5-f23b0b469701.mp4

**Comment by xiaoch05** [comment]
- [ ] When there is a network error, the authorization prompt box should not indicate the wrong address

![image](https://user-images.githubusercontent.com/15799431/171120676-5ca22645-965a-4574-8e8b-5ea034808ab8.png)

**Comment by ZolaxZola** [comment]
- [ ] Click `Transfer`, NO Response

![image](https://user-images.githubusercontent.com/102211220/171549156-28f12c14-851c-4187-a897-0970e2e7b4c5.png)

**Comment by ZolaxZola** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/102211220/173974503-adfcae01-c113-45c4-bd7e-fc0c15df1775.png">

- [ ] link was wrong, should be https://twitter.com/helixbridges
