### ISSUE TITLE
RING(Darwinia Chain)> (Darwinia Smart Chain), If entering all the transferrable amount, transaction will Fail（LiquidityRestrictions）

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#278]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

Medium

### Reproduce steps

https://darwinia.subscan.io/extrinsic/10426459-1

### Actual behavior

 entering all the transferrable amount
<img width="606" alt="image" src="https://user-images.githubusercontent.com/102211220/192213725-c65d5f3a-0cf7-4809-9f19-8cfcf971af31.png">

### Expected behavior

transact successfully

**Comment by sxlwar** [comment]
Why did I fail due to InsufficientBalance https://darwinia.subscan.io/tx/0x4b786c3d4740fcb90bfa593c1335a65fc2ff425114b3060ae377b6981c50e3d8

**Comment by ZolaxZola** [comment]
resolved.
