### ISSUE TITLE
eth v2 ORING (Pangoro Smart) > ORING (Goerli) ，Personal History Amount Error

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#281]
![image](https://user-images.githubusercontent.com/102211220/192229666-efaa9bf6-a026-4281-b0cd-94279907691c.png)
The Amount on resource chain should be` -98 `not `-88`

- [ ] The Amount on the resource chain  should contain the fee

**Comment by xiaoch05** [comment]
For Native token transfers, we deduct extra fees and show the user that the amount sent is the same as the amount received, please fix this on the transaction page.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/15799431/192235908-34158f94-2784-49b5-8400-c2efd97e689e.png">

**Comment by ZolaxZola** [comment]
Has been fixed.
![image](https://user-images.githubusercontent.com/102211220/193235082-5a495ad6-2b61-46a9-b3b4-63408ba82ebe.png)
