### ISSUE TITLE
wrong call for WORING

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#283]
It should not call native call.
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/15799431/192232728-9aac6449-fda2-4472-a92a-c9f2ec12e873.png">

**Comment by ZolaxZola** [comment]
![image](https://user-images.githubusercontent.com/102211220/194686333-51a5720a-fcc3-4074-82c8-8805afda17a9.png)
Native Call is correct. The Amount should be 10 RING and is correct now
