### ISSUE TITLE
Optimization: Improve TTFB of the homepage

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#289]
![telegram-cloud-photo-size-2-5289982180942004689-y](https://user-images.githubusercontent.com/102211220/192257420-2b5511b6-c48a-41ab-8302-05fc4d294dd7.jpg)
![telegram-cloud-photo-size-2-5301118794917330483-y](https://user-images.githubusercontent.com/102211220/192257578-9494498f-fc9c-40fc-8c47-28a8937d38d1.jpg)

 “the TTFB is really long, takes about` 5-6 seconds` for the initial load of the site, after this it's ok and fast to open the site again. have noticed this across all browsers and systems”

**Comment by sxlwar** [comment]
I think the reason for vercel, any idea? @fewensa
