### ISSUE TITLE
buglist for the dashboard & explore & detail pages

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#3]
- [x] detail page cannot be opened, error 500
- [x] twitter & github & website need update to helix related
- [x] tx time is not correct, diff 8 hours
- [x] tx time shown needs to  be accurate to the second
- [x] when search for a special address, it only shows the results from two months ago

**Comment by ZolaxZola** [comment]
- [ ] The target tx hash is not correct here. 
https://helixbridge.app/zh/transaction/0x000000000x1ce?from=darwinia&to=crab&fromMode=native&toMode=dvm
![image](https://user-images.githubusercontent.com/102211220/170216990-c7d3dea9-5e50-45db-862b-572089d278eb.png)
