### ISSUE TITLE
The transfer amount must be greater than 20.

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#304]

**Comment by ZolaxZola** [comment]
![image](https://user-images.githubusercontent.com/102211220/192716349-713fe48f-8b95-49f5-9c04-c557cde576d8.png)
When the entered amount equals 20, tx can not be sent. 
We should correct the of validation of the transfer amount as same as cBridge (>20, not >=20)
and change alert content into: `The transfer amount must be greater than 20.`

**Comment by ZolaxZola** [comment]
<img width="979" alt="image" src="https://user-images.githubusercontent.com/102211220/201030110-eb7d8169-ba54-4ef2-bbc1-f24e562ab647.png">
this issue still exists

**Comment by sxlwar** [comment]
都有哪些？还是只有这个一方向？

**Comment by sxlwar** [comment]
而且我现在觉得类似的验证并不应该在 helix 里做，helix 应该只负责验证常识性的逻辑，类似这种就应该让钱包报出来，或者让交易失败。helix 作为一个可扩展的应用，不可能知道第三方桥的特殊的验证逻辑

**Comment by ZolaxZola** [comment]
> We should correct the validation of the transfer amount as same as cBridge (>20, not >=20)

This doesn't seem to be done yet.

**Comment by xiaoch05** [comment]
所有cbridge 相关的最小限额到 20
