### ISSUE TITLE
MetaMask Popup appears in 7 seconds when transferring RING(Darwinia Smart Chain)> (Darwinia Chain)

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#321]
### Prerequisites

- [X] Are you running the latest version?

### Importance

Serious

### Priority

Medium

### Reproduce steps

transferring RING(Darwinia Smart Chain)> (Darwinia Chain)
click `confirm` 

### Actual behavior

MetaMask won't show up until wait for 6-7 seconds

### Expected behavior

MetaMask shows up immediately after clicking `Confirm Transfer`

**Comment by ZolaxZola** [comment]
![image](https://user-images.githubusercontent.com/102211220/194696720-57f85a82-2d3c-4373-a485-0937df354d4e.png)

**Comment by ZolaxZola** [comment]
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/102211220/201041632-b25fcfe8-7e69-434c-9e23-e71c832ac4f2.png">

**Comment by sxlwar** [comment]
复现不出来么，polkadot 插件出现这种情况尚可理解，metamask 不太应该

**Comment by ZolaxZola** [comment]
又试了试，在新版本里没能复现了
