### ISSUE TITLE
Chains' icons are out of fixed range.

### ISSUE THREAD

**Issue by 1022ranji** [helix-bridge/helix-ui#325]
### Importance

General

### Priority

Medium

### Description

<img width="2050" alt="image" src="https://user-images.githubusercontent.com/80877629/194834547-164e582a-f611-4a9c-a2a4-86fbcbe52184.png">

**Comment by sxlwar** [comment]
复现不出来， 首次使用的模式是会出现这种情况，后来模式改了应该不会出现才对
