### ISSUE TITLE
Show detail page before indexing

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#33]
### Topic

Function Implementation, UI Design

### Description

When the indexer has not find the transaction, we still need to provide the user with a link to the details page, only this link has incomplete information and requires the user to wait. Such as the following link.

<img width="1107" alt="Screen Shot 2022-05-31 at 1 24 55 PM" src="https://user-images.githubusercontent.com/15799431/171098949-06a82dde-2fae-484f-bd02-4c7fd9e2abfa.png">

**Comment by sxlwar** [comment]
will introduce new problems, out of our control, e.g.
On Ethereum scan, the empty address will be redirected to an error page.
https://goerli.etherscan.io/tx/null<'', 0, undefined> will be change to  https://goerli.etherscan.io/error
