### ISSUE TITLE
USDT.e(Avalanche) > USDT(Optimism) History Record

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#348]
<img width="888" alt="image" src="https://user-images.githubusercontent.com/102211220/196617914-42194082-023f-4836-9fa5-9e0aa09b1acf.png">
https://helix-stg.vercel.app/transaction/cbridge/avalanche-10-cbridge-0x087cbcdca291fbf6fe579b8bde031c97f9990e9e0d9bfbfcbd9f8b2baf35aed9?from=avalanche&to=optimism
The transaction is successful, but the transfer record has some problems.

**Comment by sxlwar** [comment]
https://github.com/helix-bridge/indexer/pull/102

**Comment by ZolaxZola** [comment]
this issue updates to https://github.com/helix-bridge/helix-ui/issues/411
