### ISSUE TITLE
Switch to the corresponding network button

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#365]
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/102211220/197958503-1c932c26-c4c2-4592-a63d-be5ba9e67719.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/102211220/197960195-0033a1af-d98d-4c8d-8c7f-a1b04edab1a5.png">

**Comment by sxlwar** [comment]
这个我看到了，太累赘了，和转账按钮有个区分就行

**Comment by ZolaxZola** [comment]
resolved
