### ISSUE TITLE
Filter bug when it's 0x.. address #76

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#368]
`All transaction history:` 
![image](https://user-images.githubusercontent.com/102211220/197972604-0417e11c-26ee-4a3f-ae46-56d8534d5492.png)
`After filtering "Crab Smart Chain" on from_chain ` 
![image](https://user-images.githubusercontent.com/102211220/197972641-31fe39a3-7409-4eb5-9421-fc7116a375ee.png)
The first result (110 xWRING, 2022/10/26) is missing after filtering.

`After Clearing filtering: 
`![image](https://user-images.githubusercontent.com/102211220/197972663-6d14dbaf-b016-45c1-b60e-5431ee642206.png)
 Results should be more than what is shown. (transactions of October are missing)

**Comment by sxlwar** [comment]
https://github.com/ant-design/ant-design/issues/38240
