### ISSUE TITLE
can't switch to bsc network

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#371]
![image](https://user-images.githubusercontent.com/15799431/198169147-17b676ea-49e3-4a96-8d81-8d82134086a4.png)

**Comment by sxlwar** [comment]
more detail to reproduce

**Comment by xiaoch05** [comment]
maybe the same issue as follows, the chain info configure error.
![image](https://user-images.githubusercontent.com/15799431/199686988-ec5f541a-c870-4a76-9370-ba7fb1489f13.png)

**Comment by xiaoch05** [comment]
https://github.com/helix-bridge/helix-ui/commit/817e9b33bf40dcc7129c2a7d892c9aac5c4b4482
