### ISSUE TITLE
should not display the same source and target network for same token

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#373]
![image](https://user-images.githubusercontent.com/15799431/198216361-d87f3442-95a5-4488-aa2c-e63d9a4b0602.png)

**Comment by sxlwar** [comment]
It is previous wormhole implementation, using two-way restrictions, but it seems that everyone does not like it very much

**Comment by xiaoch05** [comment]
fixed
![image](https://user-images.githubusercontent.com/15799431/202113602-b3147242-1da5-4dbc-86dc-2a5091323974.png)
