### ISSUE TITLE
need more design for the token selector window

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#381]
![image](https://user-images.githubusercontent.com/15799431/199388378-91814bff-cbb7-4687-90d1-18e611a9b03c.png)

**Comment by ZolaxZola** [comment]
@sxlwar 
<img width="698" alt="image" src="https://user-images.githubusercontent.com/102211220/201861074-47b016da-4fe1-4d32-b61f-05d8c1ca8806.png">
1. Increase the height of the search box(labelled1), make it not smaller than the height of transfer button. And please refers to the pic for the Inner margin 
<img width="439" alt="image" src="https://user-images.githubusercontent.com/102211220/201866149-55d7762d-deb3-42a4-8398-0c7e84f2c5a0.png">

2. Reduce width to fit content (labeled 2). 
3. Increase the height of dropbox to show more options (labeled 3).
4. display the tokens after `clicking` the chain option not after `hovering`. ( It seems has been adjusted like this already)

**Comment by sxlwar** [comment]
1. 作为一个辅助元素为什么要和放那么大的高度？
2. fit content 宽度又会变来变去，上次弹窗 fit contente 就被否了，为什么这里又要变成 fit content？宽度动态后，下拉框左对齐？右对齐？还是居中？实际上怎么对齐都不好看
3.  increase 多少？至少保证多少options显示？
4. 没改，还是 hover。要快速查看目标链上可到达的 token，为什么要增加一下 click 动作？
