### ISSUE TITLE
Results are empty on the current page when filtering the destination chain is Ethereum

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#383]
![image](https://user-images.githubusercontent.com/102211220/199390775-ce242e3c-b6b4-4c6f-b167-0b35373929bc.png)
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/102211220/199390952-49c0e87b-5c00-4a6f-b2a6-ce3397f3ff5f.png">
(have to switch to the exact page)

**Comment by xiaoch05** [comment]
https://github.com/helix-bridge/helix-ui/commit/5b96daf5fc7f09e079f79fe68951576b8b37a894
