### ISSUE TITLE
cBridge tx detail page 404

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#387]
https://helix-stg.vercel.app/transaction/cbridge/optimism-1-cbridge-0x442be18cf4703e6285724a289156dc00f353663fa58f5dc83a75a1374b7673af
<img width="961" alt="image" src="https://user-images.githubusercontent.com/102211220/199432450-6956c6b3-5648-465e-bede-947468ee5520.png">

**Comment by sxlwar** [comment]
https://helix-stg.vercel.app/records/cbridge/optimism-1-cbridge-0x442be18cf4703e6285724a289156dc00f353663fa58f5dc83a75a1374b7673af
