### ISSUE TITLE
Cannot Refund on tx detail page

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#390]
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/102211220/199636062-40d63180-7423-460f-b9d0-8d15d147ab91.png">
https://helix-stg.vercel.app/records/helix/darwiniaDVM-crabDVM/crab-dvm2darwinia-dvm-s2sv2-0x000000000x93

**Comment by xiaoch05** [comment]
fund not enough
