### ISSUE TITLE
Shall we adjust Estimate Time to be shorter？

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#402]
Except for Crab Chain <> Crab Parachain, which will be taken down, 
all the other bridge of helix takes only 1-2min or less.

15 minutes seems too long.

1. Helix : 1-3 minutes
2. cBridge: 5-20 minutes (In their docs: Most of the cross-chain transfers take 5-20 minutes to complete.)
3.  XCM ：1-3 minutes

<img width="758" alt="image" src="https://user-images.githubusercontent.com/102211220/199705719-7f52ab55-55d3-4c7d-8e87-1e1acde51241.png">

**Comment by xiaoch05** [comment]
15 Minutes is an initial configure.
When we have many history records, then we get an average time from history.
