### ISSUE TITLE
xcm support shiden & khala

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#409]
### Importance

General

### Priority

Medium

### Description

shiden
- [x] -> karura SDN/KAR/aUSD
- [x] -> moonriver SDN/MOVR
- [x] -> khala SDN/PHA

karura
- [x] -> shiden SDN/KAR/aUSD
- [x] -> moonriver aUSD/MOVR/KAR
- [x] -> khala PHA/KAR

moonriver
- [x] -> shiden xcSDN/MOVR
- [x] -> karura xcAUSD/xcKAR/MOVR
- [x] -> khala MOVR/xcPHA

khala
- [x] -> moonriver PHA/MOVR
- [x] -> shiden SDN/PHA
- [x] -> karura PHA/KAR

**Comment by sxlwar** [comment]
karura
[KAR -> shiden]( https://karura.subscan.io/extrinsic/0x256029699f0743dacb43326a6e829f8a6625c19bdfc5eb93599e3961dab3f566)
