### ISSUE TITLE
Wrong Status of  USDT.e(Avalanche) > USDT(Optimism)  transfer record

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#411]
on Helix: https://helixbridge.app/records/cbridge/avalanche-10-cbridge-0x087cbcdca291fbf6fe579b8bde031c97f9990e9e0d9bfbfcbd9f8b2baf35aed9
on cBridge: https://celerscan.com/tx/0xf29b334fd498fc783f7f25df164e9c05067fcdec857366eb368122301eb17fc7
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/102211220/200793223-cf5d03b3-989a-4ec0-9aba-c7b75863cdc8.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/102211220/200793307-45f3793f-9976-4f7f-808f-e453262f9575.png">

The status hasn't been updated
The received amount hasn't been updated

**Comment by sxlwar** [comment]
```bash
~/projects/itering/ curl -d '{ "transfer_id": "087cbcdca291fbf6fe579b8bde031c97f9990e9e0d9bfbfcbd9f8b2baf35aed9" }' https://cbridge-prod2.celer.network/v2/getTransferStatus
{
  "err": null,
  "status": 5,
  "wd_onchain": null,
  "sorted_sigs": [
  ],
  "signers": [
  ],
  "powers": [
  ],
  "refund_reason": 0,
  "block_delay": 15,
  "src_block_tx_link": "https://snowtrace.io/tx/0xf29b334fd498fc783f7f25df164e9c05067fcdec857366eb368122301eb17fc7",
  "dst_block_tx_link": "https://optimistic.etherscan.io/tx/0x1c4bea207ca290247a881592725cc0a382467930d284b5602ba05ea22fed1415",
  "bridge_type": 1
}
```
cbridge 接口返回是对的

<img width="605" alt="image" src="https://user-images.githubusercontent.com/20088392/202627861-e276e019-7e0a-47fa-9316-a173de3f54e5.png">

响应结果取错字段了? @xiaoch05

**Comment by xiaoch05** [comment]
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/15799431/209106349-8509931b-0254-4542-916c-23c762b37ef2.png">
