### ISSUE TITLE
Update the claim reminder text when the tx is pending to claim

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#413]
“Please claim the tokens on the target chain.”
<img width="540" alt="image" src="https://user-images.githubusercontent.com/102211220/201005831-050153e9-b0ff-49b4-98ba-53b0e0aef1d0.png">

**Comment by sxlwar** [comment]
什么意思

**Comment by ZolaxZola** [comment]
更新一下这边的提示文字，之前figma上有点错误，目前显示: 在源链领取，需要改成: 在目标链上领取
