### ISSUE TITLE
Cannot approve USDT on Ethereum

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#414]
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/102211220/201034136-78bb2b99-bcab-41b5-ac86-387cf0e20cae.png">

**Comment by ZolaxZola** [comment]
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/102211220/201035178-041f4ad7-841e-4789-a80f-c6ed7effe04a.png">
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/102211220/201035249-049d7ebd-e9b6-4cb7-8db3-b1cb80d43182.png">

**Comment by xiaoch05** [comment]
try again? My wallet tried to be normal
![image](https://user-images.githubusercontent.com/15799431/202593952-91932e62-3ddb-4376-9817-f8bd9a5d90c6.png)

**Comment by ZolaxZola** [comment]
![Image](https://user-images.githubusercontent.com/102211220/202613531-d0b337ac-7f3d-4ddf-9781-14d76b79bfd6.png)

think I haven't approved USDT for this contract？ It shows that I have approved when I refresh the transfer page today. Then try to transfer , it shows the same error notification

**Comment by sxlwar** [comment]
https://docs.ethers.io/v5/troubleshooting/errors/#help-UNPREDICTABLE_GAS_LIMIT

**Comment by xiaoch05** [comment]
see https://github.com/helix-bridge/helix-ui/issues/304
