### ISSUE TITLE
prompt to switch to the correct network first before approving tokens when user's wallet is connected to a different chain

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#416]
In case user's wallet is connected to a different chain when approving tokens, helix should prompt to switch to the correct network first.
![image](https://user-images.githubusercontent.com/102211220/201243274-5a23b386-915c-4aa1-831d-7ef2889c4094.png)

**Comment by sxlwar** [comment]
怎么复现连接不一致时发起 approve？

**Comment by ZolaxZola** [comment]
现在网络不一致时的提醒 即时更新了，复现不出来之前的情况了。
（ 之前好像是approve 按钮，在网络不一致时，没有及时更新成 Switch to XXX）
