### ISSUE TITLE
Darwinia/Crab's Network & Token Icons update

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#417]
https://www.notion.so/itering/Network-Token-Icons-for-Darwinia-Crab-09b7611a1a6b4e81980d34f84afbc384
<img width="830" alt="image" src="https://user-images.githubusercontent.com/102211220/201272303-ced4d219-1937-4536-bb74-b154b2d33790.png">

**Comment by sxlwar** [comment]
#406

**Comment by ZolaxZola** [comment]
as discussed conclusion: we should use the same icon for one network, and the same icon for CRAB, xWCRAB, WCRAB, and so on. It's the new material that has not been included in pr #406
