### ISSUE TITLE
Daily Limit  is missing on Pangolin Smart Chain<>Pangolin Parachain

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#421]
![image](https://user-images.githubusercontent.com/102211220/201620019-c85e664c-23e2-4dbf-86d7-e6ed9874daee.png)

**Comment by xiaoch05** [comment]
For this bridge we do not limit the daily transaction amount

**Comment by ZolaxZola** [comment]
There is no daily limit for Crab Parachain<>Crab Smart Chain for now.
