### ISSUE TITLE
Error: Can not find the chain config by darwinia

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#426]
![image](https://user-images.githubusercontent.com/102211220/202092562-6998f02c-8fbc-4a95-a465-77c417d877d1.png)
![image](https://user-images.githubusercontent.com/102211220/202092705-7716c735-74c9-4d9a-8f7f-8188757d9dad.png)
happens on testnet stg
always meet this error when I have a Darwinia account in Math Wallet

**Comment by sxlwar** [comment]
localStorage.clear()
