### ISSUE TITLE
should not change the account format when jumping to the records page (in search box and account section)

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#430]
should not change the account format when jumping to the records page,( keep the account format)
https://user-images.githubusercontent.com/102211220/202110084-1f19f158-3ed6-4cea-b408-8a60be23144d.mp4

**Comment by sxlwar** [comment]
need to remove all Polkadot account convert after multi-wallet support actually. The account format is determined by the wallet

**Comment by sxlwar** [comment]
Looks a bit weird, so changed it to let helix decide regardless of the wallet format
