### ISSUE TITLE
the other wallets should not come up after selecting a specific wallet to connect

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#435]
It happens when I select Talisman to connect, then all the wallets come up(it's just like what's in the production environment)
Think we should adjust this if we integrate the other wallets
![image](https://user-images.githubusercontent.com/102211220/202348031-02dc8221-b845-416a-9c46-d7427cdf68d2.png)

**Comment by sxlwar** [comment]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/20088392/202598113-81838adc-6efc-4145-9b86-f75b8e2da830.png">
因为就是同一个，polkadot-js 区分不出来

**Comment by ZolaxZola** [comment]
Darwinia Apps 就是可以的，选择一个波卡系钱包，只唤醒对应的钱包插件

**Comment by sxlwar** [comment]
看了下确实有办法绕过，但波卡文档里却没有推荐这个方法
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/20088392/202676466-12105c71-f744-4130-bed8-b8aed00f259a.png">

按它文档描述，就应该是这样
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/20088392/202677578-e00b388b-ae49-4b96-91f8-68810e0bfabb.png">

另外apps 里区别对待了移动端，效果也是一样

<img width="1793" alt="image" src="https://user-images.githubusercontent.com/20088392/202662543-d4f2209a-bc5e-4e1e-8c1f-ce9a384db622.png">
