### ISSUE TITLE
Failed(out of gas)  from DSC to Darwini Chain

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#439]
https://darwinia.subscan.io/extrinsic/0xad2062e9e742788e517b02892d04a2fa735561b95658da66c86d0b76875fff27
https://darwinia.subscan.io/extrinsic/0x6db9e03225ded6649053f805c306cebd9c6c14c18659926122a4eb0a3089e093
![image](https://user-images.githubusercontent.com/102211220/202380130-b8d9417c-d022-4861-adac-62986803b814.png)

**Comment by sxlwar** [comment]
这和mathwallet没关系
https://darwinia.subscan.io/extrinsic/0x604c7dc66ee94ed80544133b20fbdea0150a080d99a220b889c4069ee23c207c
