### ISSUE TITLE
can't transfer from avalanche to astar

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#449]
![image](https://user-images.githubusercontent.com/102211220/202954891-d2a3be3b-056a-413f-a60f-2d2422a2eb6c.png)

**Comment by sxlwar** [comment]
那不都提示了没有这个桥？cBridge 支持吗？

**Comment by ZolaxZola** [comment]
这个桥之前是支持的，现在cBridge不支持了
看下这种情况我们是把对应的选项去掉，还是 更新一下提示 “暂无可用桥”  @xiaoch05

**Comment by xiaoch05** [comment]
直接去掉

**Comment by ZolaxZola** [comment]
> 直接去掉

@sxlwar

**Comment by sxlwar** [comment]
https://github.com/helix-bridge/helix-ui/pull/167/files#diff-3cdb5fa0c9d57efaa0804a301e6d298611d4dc3568c505ebb84b38cfbacb4bd1R23-R46
从来就没有的东西
