### ISSUE TITLE
ui v2 test issues

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#520]
- [x] add Bridge type info when register
- [x] add allowances shown on target chain when approve

**Comment by xiaoch05** [comment]
- [ ] native token does not need approve
<img width="701" alt="image" src="https://github.com/helix-bridge/helix-ui/assets/15799431/3222f462-6b1c-40b5-b729-07cd3a78bf3f">

**Comment by xiaoch05** [comment]
- [ ] can't show goerli eth token

<img width="1245" alt="image" src="https://github.com/helix-bridge/helix-ui/assets/15799431/a00a8154-658d-4c78-a5f6-16d1d27a3557">

**Comment by xiaoch05** [comment]
- [ ] can't send 0.1 eth from goerli to arbitrum goerli
<img width="1191" alt="image" src="https://github.com/helix-bridge/helix-ui/assets/15799431/ae5a178b-02d4-4540-82a7-0ff7f8cab229">

**Comment by xiaoch05** [comment]
- [ ] type error
<img width="1193" alt="image" src="https://github.com/helix-bridge/helix-ui/assets/15799431/2ed5d8f0-2503-4f4a-b8d2-ea09c3dd0906">

**Comment by xiaoch05** [comment]
- [ ] relayer list only show baseFee, not baseFee + protocolFee

**Comment by JayJay1024** [comment]
Issues have been fixed. If have other problem, please open a new issue.
