### ISSUE TITLE
on target chain, out of gaslimit

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#650]
https://helixbridge.app/records/darwinia-dvm2crab-dvm-xtoken(lock)-0x6b767bed8d094a3374588c470d94e6685d0d6cced1664f005e572557350b97f2

https://msgscan.darwinia.network/messages/0x72234136d481896d2c71a375b91b08691e917cee030671d3d793dfce8366e9b2

**Comment by JayJay1024** [comment]
Fixed in https://github.com/helix-bridge/helix-ui/pull/647/commits/712d956eabd6ca21ff5efb8e997599e64f461459

**Comment by JayJay1024** [comment]
Confirmed that it was not a helix-ui bug, close this issue.
