### ISSUE TITLE
wrong status for xtoken bridge

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#676]
<img width="1216" alt="image" src="https://github.com/helix-bridge/helix-ui/assets/15799431/b63f7a01-bc59-4d71-b06d-517d964e4ec8">

**Comment by JayJay1024** [comment]
https://xtoken.helixbridge.app/records/crab-dvm2darwinia-dvm-sub2subv21(lock)-0x646163620xb5
<img width="366" alt="image" src="https://github.com/helix-bridge/helix-ui/assets/21007682/70710adb-6e59-4322-8420-7562aefb55af">

Doesn't `result: 0` represent `pending`

**Comment by JayJay1024** [comment]
If the problem persists, pls resubmit the issue in the xtoken repo.
