### ISSUE TITLE
wrong address format in history page sometimes

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#68]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

Medium

### Reproduce steps

1. connect Polkadot  in https://apps.helixbridge.app/history
2. connect MetaMask
3. connect Polkadot

### Actual behavior

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/102211220/174209440-fd0978f1-7c51-4c30-971e-8b2e2db7dea0.png">

### Expected behavior

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/102211220/174209735-db6f2364-7d79-4e90-b23a-6b0343c9990f.png">

### Please provide the environment you discovered this bug in

Browser: Chrome 102.0.5005.115

**Comment by sxlwar** [comment]
fixed in #67 

https://github.com/helix-bridge/helix-ui/pull/67/files#diff-ffa914177d36f950582e7754cff79d474083f0b463ebb40fb0014f5bf644a5a3
