### ISSUE TITLE
We need to modify part of the design of the transaction details page in order to differentiate among Crab Chain / Crab Parachain / Crab Smart Chain

### ISSUE THREAD

**Issue by ZolaxZola** [helix-bridge/helix-ui#76]
### Importance

General

### Priority

Medium

### Description

https://www.figma.com/file/AyxydZgzwGX66PnkRN0NdA/Helix?node-id=2712%3A11044
show the names of the chains

**Comment by sxlwar** [comment]
https://github.com/helix-bridge/helix-ui/pull/74/files#diff-8ed88ba29be3586cc23a4b9190855c81da175545276bcb9a69b4314d662d760b

Update icon after [iconfont](https://www.iconfont.cn/icons/upload) is restored
