### ISSUE TITLE
wrong tx link to subscan

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#77]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

Medium

### Reproduce steps

crab smart chain to crab

### Actual behavior

![image](https://user-images.githubusercontent.com/15799431/175440867-ebd56dac-6b36-4aa0-bef0-910f90a0adfa.png)

### Expected behavior

should be crab.subscan.io

**Comment by sxlwar** [comment]
https://github.com/helix-bridge/helix-ui/pull/74/commits/6c83af4d651623ae17498d219af929dab517db1d

fixed #74
