### ISSUE TITLE
personal history page

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#78]
### Importance

General

### Priority

High

### Description

建议个人历史记录页面使用弹对话框的方式
其主页面还是交易发送页面，这样可以延用交易页面连接的钱包来读取用户地址
后面直接跟Helix explore使用同一个API接口，但是展示内容有区别

**Comment by ZolaxZola** [comment]
Design File：https://www.figma.com/file/AyxydZgzwGX66PnkRN0NdA/Helix?node-id=0%3A569
