### ISSUE TITLE
search history by address

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#79]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

Medium

### Reproduce steps

1. Copy address from metamask
2. search history by the address
3. the result is empty

### Actual behavior

result is empty

### Expected behavior

can find history records related to this searched address

**Comment by sxlwar** [comment]
Accounts that come from thegraph are all lowercase

https://pangolin-thegraph.darwinia.network/subgraphs/name/wormhole/Sub2SubMappingTokenFactory/graphql
![image](https://user-images.githubusercontent.com/20088392/176086314-cae2d94a-0ff5-4355-801b-7036130354a2.png)

But the account in metamask is a checksum validated
